export const tasksApiUrl = 'http://localhost:3000/tasks/'
export const usersApiUrl = 'http://localhost:3000/users/'
export const usersGroupApiUrl = 'http://localhost:3000/userGroup/'
export const loginApiUrl = 'http://localhost:3000/login/'
export const i18nApiUrl = 'http://localhost:3000/i18n/'
